name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up environment
        uses: ./.github/actions/devenv/
        with:
          build: "true"

      - name: Install dependencies
        shell: devenv shell bash -- -e {0}
        run: uv sync --locked --all-extras --dev

      - name: Minimize uv cache
        shell: devenv shell bash -- -e {0}
        run: uv cache prune --ci

      - name: Run tests
        shell: devenv shell bash -- -e {0}
        run: uv run pytest

      - name: Run tests
        shell: devenv shell bash -- -e {0}
        run: uv run ruff check
